spring:
    datasource:
        druid:
            url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
            username: root
            password: qdxha123
            initial-size: 1
            min-idle: 3
            max-active: 20
            max-wait: 60000

